# Generated by Django 3.0.5 on 2020-05-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iflix', '0004_auto_20200501_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user_account',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
