# Generated by Django 3.0.5 on 2020-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iflix', '0005_auto_20200501_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='gender',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='user',
        ),
        migrations.AddField(
            model_name='user_account',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_account',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
