# Generated by Django 3.0.5 on 2020-05-02 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iflix', '0006_auto_20200502_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user_account',
            name='username',
        ),
        migrations.AddField(
            model_name='user_account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
